In [64]:
import math
from pathlib import Path
import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

import matplotlib.pyplot as plt
from matplotlib import cm 
from matplotlib.colors import from_levels_and_colors
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [65]:
df_acc = pd.read_csv("../../datasets/Merval.csv", index_col=0)
df_acc = df_acc.iloc[2:]
for c in df_acc.columns:
    df_acc[c] = df_acc[c].str.replace('.', '')
    df_acc[c] = df_acc[c].str.replace(',', '.')
    df_acc[c] = df_acc[c].astype(float)

In [67]:
df_acc = df_acc.dropna(how='all')

In [69]:
df_acc = df_acc[['HAVA','MOLI', 'LEDE', "MORI", 'MELI', 'AMZN',  'GOOGL', "ALUA", 'TXAR']]
df = df_acc.transpose()

In [71]:
df.replace(0, np.nan, inplace=True)
df_ratio = df.pct_change(axis=1) 
df_ratio.fillna(0, inplace=True)
#No es necesario escalar, estan escaladas -1 1
#df.loc[:, df.columns] = StandardScaler().fit_transform(df)

In [74]:
km = KMeans(n_clusters=3)
km.fit(df_ratio)
df_ratio.loc[:,["Cluster"]] = km.labels_

In [75]:
for i in df_ratio["Cluster"].unique():
    print("Cluster",i)
    print(df_ratio[df_ratio["Cluster"]==i].index)

Cluster 0
Index(['HAVA'], dtype='object')
Cluster 1
Index(['MOLI', 'ALUA', 'TXAR'], dtype='object')
Cluster 2
Index(['LEDE', 'MORI', 'MELI', 'AMZN', 'GOOGL'], dtype='object')

In [28]:
plt.figure(figsize=(8, 6))  # Tamaño opcional del gráfico
for i in df["Cluster"].unique():
    x = f_df[(f_df["cluster"]==i) & (f_df["error"]==0)]['bill_depth_mm']
    y = f_df[(f_df["cluster"]==i) & (f_df["error"]==0)]['bill_length_mm']
    c = f_df[(f_df["cluster"]==i) & (f_df["error"]==0)]['species']
    plt.scatter(x, y, color=colors[i])

for i in n_clu:
    x = f_df[(f_df["cluster"]==i) & (f_df["error"]==1)]['bill_depth_mm']
    y = f_df[(f_df["cluster"]==i) & (f_df["error"]==1)]['bill_length_mm']
    c = f_df[(f_df["cluster"]==i) & (f_df["error"]==1)]['species']
    plt.scatter(x, y, color=colors[i], marker='x', s=100)


plt.plot(centroids[:,0],centroids[:,1],'yo', markersize=20, label='centroides')
#plt.title(f"wss={wss:.2f}, bss={bss:.2f}, total={total:.2f}")
plt.grid(True)  # Opcional: activa la cuadrícula
plt.show()

FECHA,6/03/2024,5/03/2024,4/03/2024,3/03/2024,2/03/2024,1/03/2024,29/02/2024,28/02/2024,27/02/2024,26/02/2024,...,7/04/2023,6/04/2023,5/04/2023,4/04/2023,3/04/2023,2/04/2023,1/04/2023,31/03/2023,30/03/2023,Cluster
AGRO,-0.609975,-0.604235,-0.612485,-0.652711,-0.652711,-0.651284,-0.649884,-0.644979,-0.645560,-0.650841,...,-0.530176,-0.530176,-0.527604,-0.523977,-0.525881,-0.525881,-0.525881,-0.524529,-0.527049,0
ALUA,-0.466037,-0.458933,-0.464772,-0.511135,-0.511135,-0.504089,-0.510516,-0.509709,-0.502326,-0.498375,...,-0.451491,-0.451491,-0.447602,-0.449646,-0.453923,-0.453923,-0.453923,-0.455329,-0.452557,0
BBAR,-0.122726,-0.159286,-0.168485,-0.227157,-0.227157,-0.234258,-0.233058,-0.232718,-0.246300,-0.246736,...,-0.301426,-0.301426,-0.306897,-0.305231,-0.304190,-0.304190,-0.304190,-0.309272,-0.294793,0
BMA,0.235555,0.197907,0.204106,0.129955,0.129955,0.119445,0.149814,0.106497,0.074948,0.069151,...,-0.226034,-0.226034,-0.221794,-0.220480,-0.215628,-0.215628,-0.215628,-0.225578,-0.208009,0
BYMA,-0.576823,-0.572557,-0.579912,-0.458039,-0.458039,-0.467527,-0.474485,-0.469907,-0.472031,-0.479589,...,-0.418908,-0.418908,-0.413827,-0.410143,-0.417088,-0.417088,-0.417088,-0.418638,-0.419548,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MELI,2.058320,2.070264,2.094560,1.941871,1.941871,2.038069,2.070660,2.056137,2.052408,2.026680,...,3.330750,3.330750,3.351700,3.464851,3.505373,3.505373,3.505373,3.519595,3.397085,2
MSFT,2.224655,2.228606,2.259773,2.100221,2.100221,2.130170,2.133571,2.116651,2.065116,2.044562,...,1.241061,1.241061,1.219762,1.219952,1.218905,1.218905,1.218905,1.229856,1.223878,1
NFLX,2.030026,2.012963,2.069700,1.918044,1.918044,1.931714,1.878399,1.880416,1.868243,1.771727,...,3.397074,3.397074,3.441766,3.452364,3.465916,3.465916,3.465916,3.453070,3.427519,2
PBR,-0.620097,-0.613911,-0.622546,2.648158,2.648158,2.707209,2.684617,2.773814,2.908682,2.846720,...,1.475980,1.475980,1.474336,1.435406,1.464315,1.464315,1.464315,1.379137,1.424975,4
TSLA,1.901244,1.938635,1.995413,1.846843,1.846843,2.060932,2.074282,2.107488,2.028835,1.978182,...,1.740583,1.740583,1.766360,1.826129,1.852046,1.852046,1.852046,2.005523,1.895060,4

# backup
Ejemplo de cambio a porcentaje

In [ ]:
data = {
    'Day1': [100, 0, 300],
    'Day2': [110, 200, 0],
    'Day3': [120, 220, 310],
    'Day4': [130, 0, 330]
}

df = pd.DataFrame(data)
print("DataFrame original:")
print(df)
df.replace(0, np.nan, inplace=True)
percentage_change = df.pct_change(axis=1) 
percentage_change.fillna(0, inplace=True)
print("\nDataFrame con el porcentaje de cambio:")
print(percentage_change)